--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2/20/2022 6:49:36 PM
-- Server version: 5.7.29
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE ed_eddieshop;

--
-- Drop procedure `Proc_GetNewUserCode`
--
DROP PROCEDURE IF EXISTS Proc_GetNewUserCode;

--
-- Drop table `admin`
--
DROP TABLE IF EXISTS admin;

--
-- Drop procedure `Proc_GetCartFilter`
--
DROP PROCEDURE IF EXISTS Proc_GetCartFilter;

--
-- Drop procedure `Proc_GetCartFilterPaging`
--
DROP PROCEDURE IF EXISTS Proc_GetCartFilterPaging;

--
-- Drop procedure `Proc_GetProductById`
--
DROP PROCEDURE IF EXISTS Proc_GetProductById;

--
-- Drop procedure `Proc_GetProductFilterPaging`
--
DROP PROCEDURE IF EXISTS Proc_GetProductFilterPaging;

--
-- Drop view `cartextendview`
--
DROP VIEW IF EXISTS cartextendview CASCADE;

--
-- Drop procedure `Proc_GetCartFilter2`
--
DROP PROCEDURE IF EXISTS Proc_GetCartFilter2;

--
-- Drop view `cartextendview2`
--
DROP VIEW IF EXISTS cartextendview2 CASCADE;

--
-- Drop table `cart`
--
DROP TABLE IF EXISTS cart;

--
-- Drop procedure `Proc_GetProductFilter`
--
DROP PROCEDURE IF EXISTS Proc_GetProductFilter;

--
-- Drop view `productdetailview`
--
DROP VIEW IF EXISTS productdetailview CASCADE;

--
-- Drop procedure `Proc_GetProductDetailFilter`
--
DROP PROCEDURE IF EXISTS Proc_GetProductDetailFilter;

--
-- Drop procedure `Proc_GetProductDetailFilterPaging`
--
DROP PROCEDURE IF EXISTS Proc_GetProductDetailFilterPaging;

--
-- Drop table `productdetail`
--
DROP TABLE IF EXISTS productdetail;

--
-- Drop procedure `Proc_GetNewProductCode`
--
DROP PROCEDURE IF EXISTS Proc_GetNewProductCode;

--
-- Drop table `product`
--
DROP TABLE IF EXISTS product;

--
-- Drop procedure `Proc_Get_OrderFilter`
--
DROP PROCEDURE IF EXISTS Proc_Get_OrderFilter;

--
-- Drop procedure `Proc_Get_OrderFilterPaging`
--
DROP PROCEDURE IF EXISTS Proc_Get_OrderFilterPaging;

--
-- Drop procedure `Proc_GetAllOrder`
--
DROP PROCEDURE IF EXISTS Proc_GetAllOrder;

--
-- Drop procedure `Proc_GetNew_OrderCode`
--
DROP PROCEDURE IF EXISTS Proc_GetNew_OrderCode;

--
-- Drop table `_order`
--
DROP TABLE IF EXISTS _order;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Set default database
--
USE ed_eddieshop;

--
-- Create table `user`
--
CREATE TABLE user (
  UserID char(36) NOT NULL COMMENT 'Khoá chính',
  Name varchar(100) NOT NULL COMMENT 'Tên đăng nhập',
  Code varchar(20) NOT NULL COMMENT 'Mã người dùng',
  PassWord varchar(30) NOT NULL COMMENT 'Mật khẩu',
  DisplayName varchar(100) DEFAULT 'User' COMMENT 'Tên hiển thị',
  Type int(1) NOT NULL DEFAULT 0 COMMENT 'Loại quản trị viên',
  Description varchar(255) DEFAULT NULL COMMENT 'Mô tả',
  Email varchar(100) DEFAULT NULL COMMENT 'Email',
  Phone varchar(25) DEFAULT NULL COMMENT 'Số điện thoại',
  SessionID char(36) DEFAULT NULL COMMENT 'Id phiên đăng nhập',
  ConnectionID varchar(25) DEFAULT NULL COMMENT 'Id kết nối client',
  Language varchar(10) DEFAULT 'vi' COMMENT 'Ngôn ngữ',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Người tạo mới',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo mới',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Người chỉnh sửa',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày chỉnh sửa',
  PRIMARY KEY (UserID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
COMMENT = 'Thông tin người dùng';

--
-- Create table `_order`
--
CREATE TABLE _order (
  _OrderID char(36) NOT NULL COMMENT 'Khoá chính',
  UserID char(36) NOT NULL COMMENT 'Tham chiếu người dùng',
  OrderCode varchar(20) NOT NULL COMMENT 'Mã đơn hàng',
  Description varchar(255) DEFAULT NULL COMMENT 'Mô tả',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Người tạo mới',
  CreatedDate datetime NOT NULL COMMENT 'Ngày tạo mới',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Người chỉnh sửa',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày chỉnh sửa',
  Status int(10) DEFAULT 0 COMMENT 'Trạng thái đơn hàng (0 - Đơn hàng mới tạo đang chờ duyệt, 1 - Đơn hàng đã duyệt, 2 - Đơn hàng đã đóng gói và vận chuyển, 3 - Đơn hàng đã được giao thành công, 4 - Đã bị huỷ)',
  Quantity int(10) DEFAULT 0,
  TotalPrice decimal(18, 0) DEFAULT NULL,
  PRIMARY KEY (_OrderID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
COMMENT = 'Đơn hàng';

--
-- Create index `UK_order_OrderCode` on table `_order`
--
ALTER TABLE _order
ADD UNIQUE INDEX UK_order_OrderCode (OrderCode);

--
-- Create foreign key
--
ALTER TABLE _order
ADD CONSTRAINT FK_order_UserID FOREIGN KEY (UserID)
REFERENCES user (UserID) ON DELETE CASCADE ON UPDATE CASCADE;

DELIMITER $$

--
-- Create procedure `Proc_GetNew_OrderCode`
--
CREATE DEFINER = 'ed_eddieshop'@'%'
PROCEDURE Proc_GetNew_OrderCode ()
COMMENT 'Lấy mã đơn hàng mới'
BEGIN
  SET @prefix = 'OD-';
  SET @length = 6;
  SET @lastRecord = (SELECT
      o.OrderCode
    FROM _order o
    WHERE o.OrderCode REGEXP CONCAT(@prefix, '[0-9]{', @length, '}')
    ORDER BY o.OrderCode DESC LIMIT 1);

  SELECT
    IF(@lastRecord IS NULL,
    CONCAT(@prefix, LPAD('1', @length, '0')),
    CONCAT(@prefix, LPAD(SUBSTRING(@lastRecord, LENGTH(@prefix) + 1) + 1, @length, '0'))
    );
END
$$

--
-- Create procedure `Proc_GetAllOrder`
--
CREATE DEFINER = 'ed_eddieshop'@'%'
PROCEDURE Proc_GetAllOrder (IN filterString varchar(255), IN pageSize int(10), IN pageStart int(10))
BEGIN
  SELECT
    *
  FROM (SELECT
      o._OrderID,
      o.UserID,
      o.OrderCode,
      o.Description,
      o.CreatedBy,
      o.CreatedDate,
      o.ModifiedBy,
      o.ModifiedDate,
      o.Status,
      u.SessionID,
      o.TotalPrice,
      o.Quantity
    FROM _order o
      LEFT JOIN user u
        ON o.UserID = u.UserID) AS _OrderJoin
  WHERE (LOWER(_OrderJoin.OrderCode) LIKE CONCAT('%', LOWER(filterString), '%')
  OR LOWER(_OrderJoin.Description) LIKE CONCAT('%', LOWER(filterString), '%'))
  LIMIT pageStart, pageSize;
END
$$

--
-- Create procedure `Proc_Get_OrderFilterPaging`
--
CREATE DEFINER = 'ed_eddieshop'@'%'
PROCEDURE Proc_Get_OrderFilterPaging (IN filterString varchar(255), IN sessionID char(36), IN pageStart int(20), IN pageSize int(20))
COMMENT 'Lấy thông tin đơn hàng'
BEGIN
  SELECT
    *
  FROM (SELECT
      o._OrderID,
      o.UserID,
      o.OrderCode,
      o.Description,
      o.CreatedBy,
      o.CreatedDate,
      o.ModifiedBy,
      o.ModifiedDate,
      o.Status,
      u.SessionID,
      o.TotalPrice,
      o.Quantity
    FROM _order o
      LEFT JOIN user u
        ON o.UserID = u.UserID) AS _OrderJoin
  WHERE _OrderJoin.SessionID = sessionID
  AND (LOWER(_OrderJoin.OrderCode) LIKE CONCAT('%', LOWER(filterString), '%')
  OR LOWER(_OrderJoin.Description) LIKE CONCAT('%', LOWER(filterString), '%'))
  LIMIT pageStart, pageSize;
END
$$

--
-- Create procedure `Proc_Get_OrderFilter`
--
CREATE DEFINER = 'ed_eddieshop'@'%'
PROCEDURE Proc_Get_OrderFilter (IN filterString varchar(255), IN sessionID char(36))
COMMENT 'Lấy danh sách đơn hàng'
BEGIN
  SELECT
    *
  FROM (SELECT
      o._OrderID,
      o.UserID,
      o.OrderCode,
      o.Description,
      o.CreatedBy,
      o.CreatedDate,
      o.ModifiedBy,
      o.ModifiedDate,
      u.SessionID
    FROM _order o
      LEFT JOIN user u
        ON o.UserID = u.UserID) AS _OrderJoin
  WHERE _OrderJoin.SessionID = sessionID
  AND (LOWER(_OrderJoin.OrderCode) LIKE CONCAT('%', LOWER(filterString), '%')
  OR LOWER(_OrderJoin.Description) LIKE CONCAT('%', LOWER(filterString), '%'));
END
$$

DELIMITER ;

--
-- Create table `product`
--
CREATE TABLE product (
  ProductID char(36) NOT NULL COMMENT 'Khoá chính',
  ProductName varchar(255) NOT NULL COMMENT 'Tên sản phẩm',
  ProductCode varchar(20) NOT NULL COMMENT 'Mã sản phẩm',
  Price decimal(12, 0) NOT NULL DEFAULT 0 COMMENT 'Giá sản phẩm',
  OldPrice decimal(12, 0) DEFAULT 0 COMMENT 'Giá cũ',
  Quantity int(10) DEFAULT 0 COMMENT 'Số lượng',
  TotalPrice decimal(20, 0) DEFAULT 0 COMMENT 'Tổng tiền',
  Description varchar(255) DEFAULT NULL COMMENT 'Mô tả chi tiết',
  Image varchar(255) NOT NULL DEFAULT '' COMMENT 'Ảnh chính',
  ShowDiscount int(2) DEFAULT 0 COMMENT 'Hiển thị giảm giá',
  Discount int(10) DEFAULT NULL COMMENT 'Giảm giá',
  Sold int(10) NOT NULL DEFAULT 0 COMMENT 'Đã bán',
  Star int(2) DEFAULT 0 COMMENT 'Chấm sao',
  Hot int(2) DEFAULT 0 COMMENT 'Sản phẩm yêu thích',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Người tạo mới',
  CreatedDate datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'Ngày tạo mới',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Người chỉnh sửa',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày chỉnh sửa',
  PRIMARY KEY (ProductID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1024,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
COMMENT = 'Thông tin sản phẩm';

--
-- Create index `UK_product_ProductCode` on table `product`
--
ALTER TABLE product
ADD UNIQUE INDEX UK_product_ProductCode (ProductCode);

DELIMITER $$

--
-- Create procedure `Proc_GetNewProductCode`
--
CREATE DEFINER = 'ed_eddieshop'@'%'
PROCEDURE Proc_GetNewProductCode ()
COMMENT 'Lấy mã sản phẩm mới'
BEGIN
  SET @lastRecord = (SELECT
      p.ProductCode
    FROM product p
    WHERE p.ProductCode REGEXP 'SP-[0-9]{4}'
    ORDER BY p.ProductCode DESC LIMIT 1);

  SELECT
    IF(@lastRecord IS NULL,
    'SP-0001',
    CONCAT('SP-', LPAD((SUBSTRING(@lastRecord, 6) + 1), 4, '0'))
    );

END
$$

DELIMITER ;

--
-- Create table `productdetail`
--
CREATE TABLE productdetail (
  ProductDetailID char(36) NOT NULL COMMENT 'Khoá chính',
  ProductID char(36) NOT NULL COMMENT 'Tham chiếu sản phẩm',
  UserID char(36) NOT NULL COMMENT 'Tham chiếu người dùng',
  Comment varchar(255) DEFAULT NULL COMMENT 'Bình luận',
  Star int(10) DEFAULT NULL COMMENT 'Đánh giá',
  _Like int(2) DEFAULT 0 COMMENT 'Yêu thích',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Người tạo mới',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Người chỉnh sửa',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo mới',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày chỉnh sửa',
  PRIMARY KEY (ProductDetailID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
COMMENT = 'Thông tin sản phẩm gắn với người dùng';

--
-- Create foreign key
--
ALTER TABLE productdetail
ADD CONSTRAINT FK_productdetail_ProductID FOREIGN KEY (ProductID)
REFERENCES product (ProductID) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE productdetail
ADD CONSTRAINT FK_productdetail_UserID FOREIGN KEY (UserID)
REFERENCES user (UserID) ON DELETE CASCADE;

DELIMITER $$

--
-- Create procedure `Proc_GetProductDetailFilterPaging`
--
CREATE DEFINER = 'ed_eddieshop'@'%'
PROCEDURE Proc_GetProductDetailFilterPaging (IN filterString varchar(255), IN pageStart int, IN pageSize int(20), IN sessionID char(36))
BEGIN
  SELECT
    *
  FROM productdetail p;
END
$$

--
-- Create procedure `Proc_GetProductDetailFilter`
--
CREATE DEFINER = 'ed_eddieshop'@'%'
PROCEDURE Proc_GetProductDetailFilter (IN filterString varchar(255))
BEGIN
  SELECT
    *
  FROM productdetail p;
END
$$

DELIMITER ;

--
-- Create view `productdetailview`
--
CREATE
DEFINER = 'ed_eddieshop'@'%'
VIEW productdetailview
AS
SELECT
  `pdt`.`ProductDetailID` AS `ProductDetailID`,
  `pdt`.`ProductID` AS `ProductID`,
  `pdt`.`Comment` AS `Comment`,
  `pdt`.`Star` AS `Star`,
  `pdt`.`_Like` AS `_Like`,
  `pdt`.`CreatedBy` AS `CreatedBy`,
  `pdt`.`ModifiedBy` AS `ModifiedBy`,
  `pdt`.`CreatedDate` AS `CreatedDate`,
  `pdt`.`ModifiedDate` AS `ModifiedDate`,
  `u`.`UserID` AS `UserID`,
  `u`.`SessionID` AS `SessionID`,
  `u`.`Name` AS `Name`,
  `u`.`Code` AS `Code`,
  `u`.`PassWord` AS `PassWord`,
  `u`.`DisplayName` AS `DisplayName`,
  `u`.`Type` AS `Type`,
  `u`.`Description` AS `Description`,
  `u`.`Email` AS `Email`,
  `u`.`Phone` AS `Phone`
FROM (`productdetail` `pdt`
  LEFT JOIN `user` `u`
    ON ((`pdt`.`UserID` = `u`.`UserID`)));

DELIMITER $$

--
-- Create procedure `Proc_GetProductFilter`
--
CREATE DEFINER = 'ed_eddieshop'@'%'
PROCEDURE Proc_GetProductFilter (IN filterString varchar(255))
BEGIN
  SELECT
    p.ProductID,
    p.ProductName,
    p.ProductCode,
    p.Price,
    p.OldPrice,
    p.Quantity,
    p.Quantity - p.Sold AS AvaiableQuantity,
    p.Sold * p.Price AS SoldTotalPrice,
    p.TotalPrice,
    p.Description,
    p.Image,
    p.ShowDiscount,
    p.Discount,
    p.Sold,
    p.Star,
    p.Hot,
    p.CreatedBy,
    p.CreatedDate,
    p.ModifiedBy,
    p.ModifiedDate,
    pdvU.ProductDetailID,
    pdvU.ProductID,
    pdvU.Comment,
    pdvU.Star,
    pdvU.`_Like`,
    pdvU.CreatedBy,
    pdvU.ModifiedBy,
    pdvU.CreatedDate,
    pdvU.ModifiedDate,
    pdvU.UserID,
    pdvU.SessionID,
    pdvU.Name,
    pdvU.Code,
    pdvU.PassWord,
    pdvU.DisplayName,
    pdvU.Type,
    pdvU.Description,
    pdvU.Email,
    pdvU.Phone
  FROM product p
    LEFT JOIN (SELECT
        *
      FROM productdetailview pdv
      WHERE pdv.sessionID = sessionID) AS pdvU
      ON p.ProductID = pdvU.ProductID
  WHERE LOWER(p.ProductCode) LIKE CONCAT('%', LOWER(filterString), '%')
  OR LOWER(p.ProductName) LIKE CONCAT('%', LOWER(filterString), '%')
  OR LOWER(p.Description) LIKE CONCAT('%', LOWER(filterString), '%');
END
$$

DELIMITER ;

--
-- Create table `cart`
--
CREATE TABLE cart (
  CartID char(36) NOT NULL COMMENT 'Khoá chính',
  UserID char(36) NOT NULL COMMENT 'Tham chiếu người dùng',
  ProductID char(36) NOT NULL COMMENT 'Tham chiếu sản phẩm',
  OrderID char(36) DEFAULT NULL COMMENT 'Tham chiếu đơn hàng',
  Active int(2) NOT NULL DEFAULT 0 COMMENT 'Trạng thái (0 - còn trong giỏ hàng, 1 - trong đơn hàng)',
  CartQuantity int(20) NOT NULL COMMENT 'Số lượng',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Người tạo mới',
  CreatedDate datetime NOT NULL COMMENT 'Ngày tạo mới',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Người chỉnh sửa',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày chỉnh sửa',
  PRIMARY KEY (CartID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
COMMENT = 'Giỏ hàng';

--
-- Create foreign key
--
ALTER TABLE cart
ADD CONSTRAINT FK_cart_OrderID FOREIGN KEY (OrderID)
REFERENCES _order (_OrderID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE cart
ADD CONSTRAINT FK_cart_ProductID FOREIGN KEY (ProductID)
REFERENCES product (ProductID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE cart
ADD CONSTRAINT FK_cart_UserID FOREIGN KEY (UserID)
REFERENCES user (UserID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create view `cartextendview2`
--
CREATE
DEFINER = 'ed_eddieshop'@'%'
VIEW cartextendview2
AS
SELECT
  `p`.`ProductID` AS `ProductID`,
  `p`.`ProductName` AS `ProductName`,
  `p`.`ProductCode` AS `ProductCode`,
  `p`.`Price` AS `Price`,
  `p`.`OldPrice` AS `OldPrice`,
  (`p`.`Quantity` - `p`.`Sold`) AS `Quantity`,
  `p`.`TotalPrice` AS `TotalPrice`,
  `p`.`Description` AS `Description`,
  `p`.`Image` AS `Image`,
  `p`.`ShowDiscount` AS `ShowDiscount`,
  `p`.`Discount` AS `Discount`,
  `p`.`Sold` AS `Sold`,
  `p`.`Star` AS `Star`,
  `p`.`Hot` AS `Hot`,
  `u`.`SessionID` AS `SessionID`,
  `cart`.`CartID` AS `CartID`,
  `cart`.`UserID` AS `UserID`,
  `cart`.`Active` AS `Active`,
  `cart`.`OrderID` AS `OrderID`,
  `cart`.`CartQuantity` AS `CartQuantity`,
  `cart`.`CreatedBy` AS `CreatedBy`,
  `cart`.`CreatedDate` AS `CreatedDate`,
  `cart`.`ModifiedBy` AS `ModifiedBy`,
  `cart`.`ModifiedDate` AS `ModifiedDate`,
  (SELECT
      (CASE WHEN ((`p`.`Quantity` - `p`.`Sold`) = 0) THEN 0 WHEN ((((`p`.`Quantity` - `p`.`Sold`) - `cart`.`CartQuantity`) = 0) AND
          ((`p`.`Quantity` - `p`.`Sold`) <> 0)) THEN 1 WHEN ((((`p`.`Quantity` - `p`.`Sold`) - `cart`.`CartQuantity`) > 0) AND
          ((`p`.`Quantity` - `p`.`Sold`) <> 0)) THEN 2 WHEN ((((`p`.`Quantity` - `p`.`Sold`) - `cart`.`CartQuantity`) < 0) AND
          ((`p`.`Quantity` - `p`.`Sold`) <> 0)) THEN 3 END)) AS `Status`,
  (`cart`.`CartQuantity` * `p`.`Price`) AS `CartTotalPrice`
FROM ((`cart`
  LEFT JOIN `product` `p`
    ON ((`cart`.`ProductID` = `p`.`ProductID`)))
  LEFT JOIN `user` `u`
    ON ((`cart`.`UserID` = `u`.`UserID`)));

DELIMITER $$

--
-- Create procedure `Proc_GetCartFilter2`
--
CREATE DEFINER = 'ed_eddieshop'@'%'
PROCEDURE Proc_GetCartFilter2 ()
BEGIN
  SELECT
    *
  FROM cartextendview2 c;
END
$$

DELIMITER ;

--
-- Create view `cartextendview`
--
CREATE
DEFINER = 'ed_eddieshop'@'%'
VIEW cartextendview
AS
SELECT
  `p`.`ProductID` AS `ProductID`,
  `p`.`ProductName` AS `ProductName`,
  `p`.`ProductCode` AS `ProductCode`,
  `p`.`Price` AS `Price`,
  `p`.`OldPrice` AS `OldPrice`,
  (`p`.`Quantity` - `p`.`Sold`) AS `Quantity`,
  `p`.`TotalPrice` AS `TotalPrice`,
  `p`.`Description` AS `Description`,
  `p`.`Image` AS `Image`,
  `p`.`ShowDiscount` AS `ShowDiscount`,
  `p`.`Discount` AS `Discount`,
  `p`.`Sold` AS `Sold`,
  `p`.`Star` AS `Star`,
  `p`.`Hot` AS `Hot`,
  `u`.`SessionID` AS `SessionID`,
  `cart`.`CartID` AS `CartID`,
  `cart`.`UserID` AS `UserID`,
  `cart`.`Active` AS `Active`,
  `cart`.`OrderID` AS `OrderID`,
  `cart`.`CartQuantity` AS `CartQuantity`,
  `cart`.`CreatedBy` AS `CreatedBy`,
  `cart`.`CreatedDate` AS `CreatedDate`,
  `cart`.`ModifiedBy` AS `ModifiedBy`,
  `cart`.`ModifiedDate` AS `ModifiedDate`,
  (SELECT
      (CASE WHEN ((`p`.`Quantity` - `p`.`Sold`) = 0) THEN 0 WHEN ((((`p`.`Quantity` - `p`.`Sold`) - `cart`.`CartQuantity`) = 0) AND
          ((`p`.`Quantity` - `p`.`Sold`) <> 0)) THEN 1 WHEN ((((`p`.`Quantity` - `p`.`Sold`) - `cart`.`CartQuantity`) > 0) AND
          ((`p`.`Quantity` - `p`.`Sold`) <> 0)) THEN 2 WHEN ((((`p`.`Quantity` - `p`.`Sold`) - `cart`.`CartQuantity`) < 0) AND
          ((`p`.`Quantity` - `p`.`Sold`) <> 0)) THEN 3 END)) AS `Status`,
  (`cart`.`CartQuantity` * `p`.`Price`) AS `CartTotalPrice`
FROM ((`cart`
  LEFT JOIN `product` `p`
    ON ((`cart`.`ProductID` = `p`.`ProductID`)))
  LEFT JOIN `user` `u`
    ON ((`cart`.`UserID` = `u`.`UserID`)))
WHERE (`cart`.`Active` <> 1);

DELIMITER $$

--
-- Create procedure `Proc_GetProductFilterPaging`
--
CREATE DEFINER = 'ed_eddieshop'@'%'
PROCEDURE Proc_GetProductFilterPaging (IN filterString varchar(255), IN pageStart int(20), IN pageSize int(20), IN sessionID char(36))
BEGIN
  SELECT
    pdv.ProductDetailID,
    pdv.Comment,
    pdv.Star,
    pdv.`_Like`,
    pdv.UserID,
    (cev.CartID IS NOT NULL) AS InCart,
    pd.ProductID,
    ProductName,
    ProductCode,
    Price,
    OldPrice,
    Quantity,
    pd.Quantity - pd.Sold AS AvaiableQuantity,
    pd.Sold * pd.Price AS SoldTotalPrice,
    TotalPrice,
    Description,
    Image,
    ShowDiscount,
    Discount,
    Sold,
    Hot,
    CreatedBy,
    CreatedDate,
    ModifiedBy,
    ModifiedDate
  FROM product pd
    LEFT JOIN (SELECT
        p.ProductDetailID,
        p.ProductID,
        p.Comment,
        p.Star,
        p.`_Like`,
        p.UserID
      FROM productdetailview p
      WHERE p.SessionID = sessionID) AS pdv
      ON pd.ProductID = pdv.ProductID
    LEFT JOIN (SELECT
        c.ProductID,
        c.SessionID,
        c.CartID
      FROM cartextendview c
      WHERE c.SessionID = sessionID) AS cev
      ON cev.ProductID = pd.ProductID
  WHERE LOWER(pd.ProductCode) LIKE CONCAT('%', LOWER(filterString), '%')
  OR LOWER(pd.ProductName) LIKE CONCAT('%', LOWER(filterString), '%')
  OR LOWER(pd.Description) LIKE CONCAT('%', LOWER(filterString), '%')
  LIMIT pageStart, pageSize;
END
$$

--
-- Create procedure `Proc_GetProductById`
--
CREATE DEFINER = 'ed_eddieshop'@'%'
PROCEDURE Proc_GetProductById (IN ProductID char(36))
COMMENT 'Lấy sản phẩm theo id'
BEGIN
  SELECT
    pdv.ProductDetailID,
    pdv.Comment,
    pdv.Star,
    pdv.`_Like`,
    pdv.UserID,
    (cev.CartID IS NOT NULL) AS InCart,
    pd.ProductID,
    ProductName,
    ProductCode,
    Price,
    OldPrice,
    Quantity,
    TotalPrice,
    Description,
    Image,
    ShowDiscount,
    Discount,
    Sold,
    Hot,
    CreatedBy,
    CreatedDate,
    ModifiedBy,
    ModifiedDate
  FROM product pd
    LEFT JOIN (SELECT
        p.ProductDetailID,
        p.ProductID,
        p.Comment,
        p.Star,
        p.`_Like`,
        p.UserID
      FROM productdetailview p
      WHERE p.SessionID = sessionID) AS pdv
      ON pd.ProductID = pdv.ProductID
    LEFT JOIN (SELECT
        c.ProductID,
        c.SessionID,
        c.CartID
      FROM cartextendview c
      WHERE c.SessionID = sessionID) AS cev
      ON cev.ProductID = pd.ProductID
  WHERE pd.ProductID = ProductID;
END
$$

--
-- Create procedure `Proc_GetCartFilterPaging`
--
CREATE DEFINER = 'ed_eddieshop'@'%'
PROCEDURE Proc_GetCartFilterPaging (IN filterString varchar(255), IN pageStart int(20), IN pageSize int(20), IN sessionID char(36))
BEGIN
  SELECT
    c.ProductID,
    c.ProductName,
    c.ProductCode,
    c.Price,
    c.OldPrice,
    c.Quantity,
    c.TotalPrice,
    c.Description,
    c.Image,
    c.ShowDiscount,
    c.Discount,
    c.Sold,
    c.Star,
    c.Hot,
    c.SessionID,
    c.CartID,
    c.UserID,
    c.Active,
    c.CartQuantity,
    c.CreatedBy,
    c.CreatedDate,
    c.ModifiedBy,
    c.ModifiedDate,
    c.Status,
    c.CartTotalPrice
  FROM cartextendview c
    JOIN (SELECT
        u.UserID
      FROM user u
      WHERE u.SessionID = sessionID) AS u
      ON c.UserID = u.UserID
    LEFT JOIN product p
      ON c.ProductID = p.ProductID
  WHERE LOWER(p.ProductCode) LIKE CONCAT('%', LOWER(filterString), '%')
  OR LOWER(p.ProductName) LIKE CONCAT('%', LOWER(filterString), '%')
  OR LOWER(p.Description) LIKE CONCAT('%', LOWER(filterString), '%')
  LIMIT pageStart, pageSize;
END
$$

--
-- Create procedure `Proc_GetCartFilter`
--
CREATE DEFINER = 'ed_eddieshop'@'%'
PROCEDURE Proc_GetCartFilter (IN filterString varchar(255), IN sessionID char(36))
BEGIN
  SELECT
    c.ProductID,
    c.ProductName,
    c.ProductCode,
    c.Price,
    c.OldPrice,
    c.Quantity,
    c.Quantity - c.Sold AS AvaiableQuantity,
    c.TotalPrice,
    c.Description,
    c.Image,
    c.ShowDiscount,
    c.Discount,
    c.Sold,
    c.Star,
    c.Hot,
    c.SessionID,
    c.CartID,
    c.UserID,
    c.Active,
    c.CartQuantity,
    c.CreatedBy,
    c.CreatedDate,
    c.ModifiedBy,
    c.ModifiedDate,
    c.Status,
    c.CartTotalPrice
  FROM cartextendview c
    JOIN (SELECT
        u.UserID
      FROM user u
      WHERE u.SessionID = sessionID) AS u
      ON c.UserID = u.UserID
    LEFT JOIN product p
      ON c.ProductID = p.ProductID
  WHERE LOWER(p.ProductCode) LIKE CONCAT('%', LOWER(filterString), '%')
  OR LOWER(p.ProductName) LIKE CONCAT('%', LOWER(filterString), '%')
  OR LOWER(p.Description) LIKE CONCAT('%', LOWER(filterString), '%');
END
$$

DELIMITER ;

--
-- Create table `admin`
--
CREATE TABLE admin (
  AdminID char(36) NOT NULL COMMENT 'Khoá chính',
  Name varchar(100) NOT NULL COMMENT 'Tên đăng nhập',
  Code varchar(20) NOT NULL COMMENT 'Mã quản trị viên',
  PassWord varchar(30) NOT NULL COMMENT 'Mật khẩu',
  DisplayName varchar(100) NOT NULL DEFAULT 'Admin' COMMENT 'Tên hiển thị',
  Type int(1) NOT NULL DEFAULT 0 COMMENT 'Loại quản trị viên',
  Description varchar(255) DEFAULT NULL COMMENT 'Mô tả',
  Email varchar(100) DEFAULT NULL COMMENT 'Email',
  Phone varchar(25) DEFAULT NULL COMMENT 'Số điện thoại',
  SessionID char(36) DEFAULT NULL COMMENT 'Id phiên đăng nhập',
  Language varchar(10) DEFAULT 'vi' COMMENT 'Ngôn ngữ',
  ConnectionID varchar(25) DEFAULT NULL COMMENT 'Id kết nối client',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Người tạo mới',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo mới',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Người chỉnh sửa',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày chỉnh sửa',
  PRIMARY KEY (AdminID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
COMMENT = 'Thông tin quản trị viên';

DELIMITER $$

--
-- Create procedure `Proc_GetNewUserCode`
--
CREATE DEFINER = 'ed_eddieshop'@'%'
PROCEDURE Proc_GetNewUserCode ()
COMMENT 'Lấy mã người dùng mới'
BEGIN
  SELECT
    CONCAT('USER-', LPAD((SUBSTRING((SELECT
        u.Code
      FROM user u
      WHERE u.code REGEXP 'USER-[0-9]{4}'
      ORDER BY u.code DESC LIMIT 1), 6) + 1), 4, '0'));
END
$$

DELIMITER ;

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
('146d98da-0ce8-4ae8-bfd7-800406050547', 'username0013', 'USER-0012', '12345678@User', 'Trần Mạnh Quang', 0, NULL, NULL, NULL, '3f87ad16-84a2-408c-9537-f61abb2cea0e', 'PwUEmPYstqg57BGH0j_Kiw', NULL, NULL, '2021-12-06 22:33:11', NULL, NULL),
('1731fa87-79fd-4cc1-6978-553c0310877a', 'username0001', 'User-0001', '12345678@User', 'Nguyễn Tiến Dũng', 0, 'Suscipit et sed. Doloribus consequuntur ea. Dolores eius et. Nihil blanditiis voluptates. Iste fugit similique? Quia qui et. Ut assumenda vero. Natus...', 'user0001@gmail.com', '(465) 098-1888', '64cb9b71-37f4-4244-90b1-0d2b3be2374f', 'ISHgDimRC4UDbmHJsx0ejA', 'vi', 'NTDUNG', '2016-09-21 05:35:43', 'NTDUNG', '1975-01-07 07:45:20'),
('185f84ed-4563-51a0-cac7-6c0aeb6ec302', 'username0002', 'User-0002', '12345678@User', 'Nguyễn Đình Hải Dương', 0, 'Facilis animi a. Fugiat saepe inventore; et eum animi. Ut tenetur animi. Aspernatur et veniam. Quae placeat dolorem. Voluptas dolores unde. Ea vel sit. Sed.', 'user0005@gmail.com', '(784) 105-7292', 'bcada7df-7998-48d9-bca4-2839ea3116ad', '9-i0Vx9LdHCAfaTGSNafQw', 'vi', 'NTDUNG', '2002-08-31 23:39:28', 'NTDUNG', '2017-04-17 18:59:15'),
('19165ed7-212e-21c4-0428-030d4265475f', 'username0003', 'User-0003', '12345678@User', 'Nguyễn Phương Hoa', 1, 'Eaque commodi est. Qui at optio; rem quisquam sit. Nemo et nihil; ut libero ea. Beatae est unde? Et est aut.', 'user0006@gmail.com', '(141) 952-2282', '34c970dd-fd6a-4b2f-b921-d69b08a97e5f', '31170', 'vi', 'NTDUNG', '1998-03-13 20:26:43', 'NTDUNG', '1990-12-17 04:56:05'),
('27366e4a-5248-12e3-e312-ebbbcf065d1c', 'username0004', 'User-0004', '12345678@User', 'Nguyễn Mỹ Hạnh', 0, NULL, NULL, NULL, '9cde5624-441d-46f2-a6dd-98420adfa38d', '41347', 'vi', NULL, NULL, NULL, NULL),
('2924c34d-68f1-1d0a-c9c7-6c0aeb6ec302', 'username0005', 'User-0005', '12345678@User', 'Nguyễn Phương Thảo', 1, 'Quisquam ut suscipit accusantium omnis vero alias.', 'user0003@gmail.com', '(450) 290-3993', '5a702c0f-3aa4-4d53-afd3-39c383236258', '25421', 'vi', 'NTDUNG', '1974-06-22 22:31:21', 'NTDUNG', '1970-01-01 00:31:40'),
('3631011e-4559-4ad8-b0ad-cb989f2177da', 'username0006', 'User-0006', '12345678@User', 'Đào Thị Anh', 0, 'Aliquam perspiciatis quasi. Necessitatibus voluptas quos. Omnis minus voluptatem? Tempora earum quidem. Cum tempore porro. Est tempora error. Qui error et.', 'user0009@gmail.com', '(423) 916-0439', 'be08c9e6-98ea-42c2-b50c-23b93773e057', '77059', 'vi', 'NTDUNG', '1971-03-25 02:56:21', 'NTDUNG', '1970-01-01 00:00:07'),
('471530a2-44fe-7395-b1ad-cb989f2177da', 'username0007', 'User-0007', '12345678@User', 'Nguyễn Đình Mạnh', 1, 'Aut sunt delectus. Delectus voluptatem molestias fugiat! Maiores ipsum magni nam et vel. Et dolorem illo! Officia doloremque unde.', 'user0005@gmail.com', '(730) 123-8017', 'a208691f-5887-4756-9e43-517d618744cb', '64201', 'vi', 'NTDUNG', '1970-01-01 00:08:53', 'NTDUNG', '1992-07-19 23:11:29'),
('47f05e6b-4612-4249-af92-5959271fb9e0', 'username0012', 'USER-0011', '12345678@User', NULL, 0, NULL, NULL, NULL, '2bb359ee-35bc-4692-b75e-3ef126041bda', NULL, NULL, NULL, '2021-12-06 22:30:13', NULL, NULL),
('4cf2dd43-5f4b-71b6-e212-ebbbcf065d1c', 'username0008', 'User-0008', '12345678@User', 'Trần Văn Hiểu', 1, 'Qui harum officiis. Unde repellendus beatae cumque. Nulla nihil quo rerum consequuntur dolorem? Ea alias omnis quos sit maxime. Laudantium adipisci culpa...', 'user0007@gmail.com', '(465) 824-3043', '5d5c8dce-2c66-4bd1-b8b0-089e73ef8974', '26120', 'vi', 'NTDUNG', '1974-03-07 08:35:55', 'NTDUNG', '1970-01-01 00:00:01'),
('5f7b48e5-16f9-2f2f-ecdc-845b5dcdad45', 'username0009', 'User-0009', '12345678@User', 'Bùi Anh Tuấn', 0, 'Quia aut commodi. Est aut iure delectus iusto. Animi non perspiciatis quis ut quia! Quaerat numquam et quia blanditiis voluptas eius. Voluptatem fuga et...', 'user0006@gmail.com', '(219) 687-2284', '97692b7e-191d-4d44-9d1b-05c80f1a82dc', 'srx9WC1sVq1-973_9YvSzg', 'vi', 'NTDUNG', '2002-11-05 04:58:39', 'NTDUNG', '1977-12-08 05:26:23'),
('6e38ff3f-d659-4084-867a-d520480f1222', 'username0014', 'USER-0013', '12345678@User', NULL, 0, NULL, NULL, NULL, '6c3ed480-8c1e-4b0a-8957-9711a1d8c5b9', 'x19H5a8s3aqqVy06avmCfg', NULL, NULL, '2021-12-08 16:28:06', NULL, NULL),
('7a0b757e-41eb-4df6-c6f8-494a84b910f4', 'username0010', 'User-0010', '12345678@User', 'Đinh Mạnh Ninh', 0, 'Error nesciunt illum. Vel ad dolorum. Voluptas soluta fugit; distinctio fugit vel? Eum quia et. Omnis sit expedita. Natus minus nobis!', 'user0005@gmail.com', '(375) 580-5172', '73e2e8ec-a43c-4221-a15a-c681e660b5ab', 'sOO3I9HPih-DdjvzmIPo4g', 'vi', 'NTDUNG', '1994-08-12 16:56:12', 'NTDUNG', '1970-01-01 00:00:09');

-- 
-- Dumping data for table _order
--
INSERT INTO _order VALUES
('5b5d4653-1f6f-4705-be3e-20bf17da49d3', '1731fa87-79fd-4cc1-6978-553c0310877a', 'OD-000001', 'Capo', 'Nguyễn Tiến Dũng', '2022-02-20 18:41:40', NULL, NULL, 3, 3, 300000);

-- 
-- Dumping data for table product
--
INSERT INTO product VALUES
('0217fa0e-9d09-4709-9c22-97c14b1c3ea4', '[Sách] Bàn có 5 chỗ ngồi - Nguyễn Nhật Ánh', 'SP-0013', 40000, NULL, 20, 800000, '[Sách] Bàn có 5 chỗ ngồi - Nguyễn Nhật Ánh', 'https://ik.imagekit.io/uvn3cxjawn6/Product/Bàn_có_5_chỗ_ngồi_Q58PElkNO.jpg', NULL, NULL, 0, NULL, NULL, NULL, '2022-02-20 11:13:54', NULL, NULL),
('0e57c5bf-3327-40e8-af2e-30abf457739f', 'Ổ cắm điện LIOA', 'SP-0008', 20000, NULL, 100, 2000000, 'Ổ cắm điện LIOA', 'https://ik.imagekit.io/uvn3cxjawn6/Product/Ổ_cắm_điện_OtmiN9ohR.jpg', NULL, NULL, 0, NULL, NULL, NULL, '2022-02-20 11:05:43', NULL, NULL),
('15772d0b-7e73-49e3-8b21-bbef0954338f', '[Sách] Tôi thấy hoa vàng trên cỏ xanh - Nguyễn Nhật Ánh', 'SP-0016', 50000, NULL, 200, 10000000, '[Sách] Tôi thấy hoa vàng trên cỏ xanh - Nguyễn Nhật Ánh', 'https://ik.imagekit.io/uvn3cxjawn6/Product/Tôi_thấy_hoa_vàng_trên_cỏ_xanh_Q6UGswe1T.jpg', NULL, NULL, 4, NULL, NULL, NULL, '2022-02-20 11:20:02', NULL, '2022-02-20 15:13:01'),
('3df84d02-be2d-4e6f-b9a6-6c84476af836', 'USB HUB 3.0', 'SP-0006', 100000, NULL, 20, 2000000, 'USB HUB 3.0', 'https://ik.imagekit.io/uvn3cxjawn6/Product/UsbHub_tsFZQoMaK.jpg', NULL, NULL, 0, NULL, NULL, NULL, '2022-02-20 11:04:27', NULL, NULL),
('45be59da-2dc4-44e6-8c05-23d58d8ba49e', 'Điều khiển Tivi', 'SP-0004', 67000, NULL, 100, 6700000, 'Điều khiển TV siêu xịn', 'https://ik.imagekit.io/uvn3cxjawn6/Product/Điều_khiển_icLCD1u4OIb.jpg', NULL, NULL, 0, NULL, NULL, NULL, '2022-02-20 11:03:17', NULL, NULL),
('549815c0-b25f-4b42-bd2d-d957eaa0e980', 'Sạc dự phòng AVA', 'SP-0012', 300000, NULL, 23, 6900000, 'Sạc dự phòng AVA màu xanh cực nổi', 'https://ik.imagekit.io/uvn3cxjawn6/Product/Sạc_dự_phòng_iga53kGZIsz.jpg', NULL, NULL, 11, NULL, NULL, NULL, '2022-02-20 11:08:49', NULL, '2022-02-20 18:39:24'),
('5b80967c-0705-456c-b7c0-ed7a97e252f8', 'Đàn violin', 'SP-0011', 30000000, NULL, 60, 1800000000, 'Đàn violin âm thanh cực ấm, cực chuyên nghiệp', 'https://ik.imagekit.io/uvn3cxjawn6/Product/Đàn_violin_xZNZmOkdH.jpg', NULL, NULL, 12, NULL, NULL, NULL, '2022-02-20 11:07:47', NULL, '2022-02-20 17:41:53'),
('5c525b60-63db-4179-bdab-6967d08cbc26', 'Chuột máy tính Led xanh', 'SP-0005', 2000000, NULL, 23, 46000000, 'Chuột máy tính Led xanh', 'https://ik.imagekit.io/uvn3cxjawn6/Product/Chuột_MftVWkG0uhK.jpg', NULL, NULL, 0, NULL, NULL, NULL, '2022-02-20 11:03:57', NULL, NULL),
('7ab82438-12af-4458-8b57-1934c9b204e9', 'Bàn tích hợp kệ hiện đại', 'SP-0014', 1400000, NULL, 10, 14000000, 'Bàn tích hợp kệ hiện đại', 'https://ik.imagekit.io/uvn3cxjawn6/Product/Bàn_kệ_tủ_DcrpQA3x1IO.jpg', NULL, NULL, 0, NULL, NULL, NULL, '2022-02-20 11:14:43', NULL, NULL),
('83a824f9-0b2d-44de-a66e-4be4fae058b3', 'Loa máy tính trắng chất lượng cao', 'SP-0009', 7000000, NULL, 20, 140000000, 'Loa máy tính trắng chất lượng cao', 'https://ik.imagekit.io/uvn3cxjawn6/Product/LOa_URQKfSsr16.png', NULL, NULL, 0, NULL, NULL, NULL, '2022-02-20 11:06:33', NULL, NULL),
('96838ef5-0a74-4ab4-aeaa-928c0e32d319', 'Đàn Guitar', 'SP-0003', 1500000, NULL, 20, 30000000, 'Đàn Guitar cổ điển chơi siêu hay', 'https://ik.imagekit.io/uvn3cxjawn6/Product/Guitar_Q5PKqBwhCV_.jpg', NULL, NULL, 6, NULL, NULL, NULL, '2022-02-20 10:59:30', NULL, '2022-02-20 17:40:19'),
('9ecc8734-63c9-49a7-b4bc-9ff858aa0942', 'Tai nghe Prolink', 'SP-0007', 5000000, NULL, 10, 50000000, 'Tai nghe Prolink với chất lượng âm thanh cực đỉnh, cực chất', 'https://ik.imagekit.io/uvn3cxjawn6/Product/Tai_nghe_mTCmFWBKm.jpg', NULL, NULL, 6, NULL, NULL, NULL, '2022-02-20 11:05:14', NULL, '2022-02-20 16:26:52'),
('a1b009e9-7fbe-4778-81e2-d89039b50e00', 'Case máy tính', 'SP-0002', 2000000, NULL, 10, 20000000, 'Case máy tính siêu xịn', 'https://ik.imagekit.io/uvn3cxjawn6/Product/Case_máy_tính_dZ9TFWQ5v.png', NULL, NULL, 0, NULL, NULL, NULL, '2022-02-20 10:59:02', NULL, NULL),
('c0a89754-958e-4109-b60f-c013305dd84f', 'Máy tính laptop Dell', 'SP-0010', 20000000, NULL, 10, 200000000, 'Máy tính laptop Dell', 'https://ik.imagekit.io/uvn3cxjawn6/Product/Máy_tính_JIZvGWLsuDK.jpg', NULL, NULL, 0, NULL, NULL, NULL, '2022-02-20 11:07:09', NULL, NULL),
('da3c068b-0aa7-4a6a-b999-76b10d398738', 'Capo', 'SP-0015', 100000, NULL, 20, 2000000, 'Capo ', 'https://ik.imagekit.io/uvn3cxjawn6/Product/Capo_Q_kdZ6B_A.jpg', NULL, NULL, 16, NULL, NULL, NULL, '2022-02-20 11:15:07', NULL, '2022-02-20 18:41:40'),
('db7426be-7ac8-4ace-abdb-52cd6cffbcab', 'Đèn học', 'SP-0001', 900000, NULL, 10, 9000000, 'Đèn học siêu xịn', 'https://ik.imagekit.io/uvn3cxjawn6/Product/Đèn_học_NIgVZflLo.jpg', NULL, NULL, 0, NULL, NULL, NULL, '2022-02-20 10:55:54', NULL, NULL);

-- 
-- Dumping data for table productdetail
--
INSERT INTO productdetail VALUES
('65021fd5-b8f3-43a8-8c4c-e097a5f7deb0', '3df84d02-be2d-4e6f-b9a6-6c84476af836', '1731fa87-79fd-4cc1-6978-553c0310877a', NULL, 0, 1, NULL, NULL, '2022-02-20 15:10:37', NULL),
('7643107d-4d44-4c32-ae82-0c1b6815823b', '7ab82438-12af-4458-8b57-1934c9b204e9', '1731fa87-79fd-4cc1-6978-553c0310877a', 'Chiếc bàn rất tuyệt', 5, 0, NULL, NULL, '2022-02-20 15:03:46', NULL),
('7ad0ea96-d126-45e9-bcae-3b78c00c87a3', '0217fa0e-9d09-4709-9c22-97c14b1c3ea4', '1731fa87-79fd-4cc1-6978-553c0310877a', NULL, 0, 1, NULL, NULL, '2022-02-20 14:28:36', NULL),
('cbd06b2d-808a-4b78-8851-61f2ba2fb6b9', '5b80967c-0705-456c-b7c0-ed7a97e252f8', '1731fa87-79fd-4cc1-6978-553c0310877a', 'Đàn chưa được tốt. Cần nâng cao chất lượng', 3, 1, NULL, NULL, '2022-02-20 15:12:06', NULL),
('dde42d42-c3bf-4dec-ac93-4450fb4cafeb', 'da3c068b-0aa7-4a6a-b999-76b10d398738', '1731fa87-79fd-4cc1-6978-553c0310877a', NULL, 0, 0, NULL, NULL, '2022-02-20 14:28:21', NULL),
('df67ed81-a80d-4011-9a3b-a5ca184bcb21', '96838ef5-0a74-4ab4-aeaa-928c0e32d319', '1731fa87-79fd-4cc1-6978-553c0310877a', NULL, 0, 1, NULL, NULL, '2022-02-20 14:29:02', NULL),
('fc0ce154-f3db-480f-9286-763594109a56', '549815c0-b25f-4b42-bd2d-d957eaa0e980', '1731fa87-79fd-4cc1-6978-553c0310877a', 'Sản phẩm khá tốt', 4, 1, NULL, NULL, '2022-02-20 14:28:53', NULL);

-- 
-- Dumping data for table cart
--
INSERT INTO cart VALUES
('a40f001a-a442-4a65-b93f-f5231ba3b452', '1731fa87-79fd-4cc1-6978-553c0310877a', 'da3c068b-0aa7-4a6a-b999-76b10d398738', '5b5d4653-1f6f-4705-be3e-20bf17da49d3', 1, 3, NULL, '2022-02-20 18:41:25', NULL, '2022-02-20 17:46:51');

-- 
-- Dumping data for table admin
--
INSERT INTO admin VALUES
('142cb08f-7c31-21fa-8e90-67245e8b283e', 'admin001', 'ADMIN-001', '12345678@Admin', 'Nguyễn Tiến Dũng', 0, 'Quản trị viên ed_eddieshop', 'dungnt@gmai.com', '0123456789', '84f63884-5a0c-4b6a-aaf9-1acbc638e498', 'vi', 'qdTQu_EFk7o2_0h-7-Hxfw', 'NTDUNG', '1970-01-01 00:07:13', 'NTDUNG', '1970-01-01 00:00:04'),
('469b3ece-744a-45d5-957d-e8c757976496', 'admin002', 'ADMIN-002', '12345678@Admin', 'Nguyễn Phương Thảo', 1, 'Quản trị viên ed_eddieshop', 'dungnt@gmai.com', '0123456789', 'fdfa7a8d-2fc9-4ce6-bf1f-0ef69379e529', 'vi', '57cdf8c4-47e3-5560-7e41-c', 'NTDUNG', '1986-12-14 19:08:29', 'NTDUNG', '2005-08-18 12:14:49');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;